openapi: 3.1.0
info:
  title: Company Certificate Notification API
  description: APIs for requesting and accepting company certificates. Note that the Certificate Provider APIs and the Certificate Consumer APIs are available via different EDC assets.
  version: 1.0.0
tags:
  - name: Certificate Provider
    description: API endpoints offered by the Certificate Provider
  - name: Certificate Consumer
    description: API endpoints offered by the Certificate Consumer

components:
  schemas:
    Header:
      type: object
      required:
        - senderBpn
        - context
        - messageId
        - receiverBpn
        - sentDateTime
        - version
      properties:
        senderBpn:
          type: string
          description: The BPNL of the legal entity which send this request
          examples:
            - "BPNL0000000001AB"
        messageId:
          type: string
          format: uuid
          description: Identifier for this specific request being sent
          examples:
            - "3b4edc05-e214-47a1-b0c2-1d831cdd9ba9"
        context:
          type: string
          description: The type of use case this request belongs to
          enum:
            - "CompanyCertificateManagement-CCMAPI-Push:1.0.0"
            - "CompanyCertificateManagement-CCMAPI-Request:1.0.0"
            - "CompanyCertificateManagement-CCMAPI-Feedback:1.0.0"
            - "CompanyCertificateManagement-CCMAPI-Available:1.0.0"
        receiverBpn:
          type: string
          description: The intended receiver legal entity BPNL of this request
          examples:
            - "BPNL0000000002CD"
        sentDateTime:
          type: string
          description: The full time and date with timezone on when this request has been sent by the sender
          format: date-time
          examples:
            - "2025-05-04T00:00:00-07:00Z"
        version:
          type: string
          examples:
            - "3.1.0"

    FeedbackUrlHeader:
      allOf:
        - $ref: '#/components/schemas/Header'
        - type: object
          properties:
            senderFeedbackUrl:
              type: string
              description: The DSP URL from where the sender of the request expectes to receive feedback
              examples:
                - "https://domain.tld/path/to/edc/api/v1/dsp"


    CertificateRequest:
      type: object
      required:
        - header
        - content
      properties:
        header:
          $ref: '#/components/schemas/Header'
        content:
          type: object
          required:
            - certifiedBpn
            - certificateType
          properties:
            certifiedBpn:
              type: string
              description: The BPNL of the legal entity for which the requested certificate has been issued
              pattern: "^BPNL[A-Z0-9]{12}$"
              examples:
                - "BPNL0000000002CD"
            certificateType:
              type: string
              description: The type of certificate the certificate consumer requests
              examples:
                - "iso9001"
            locationBpns:
              type: array
              description: The BPNs of the site or address locations for which the certificate consumer requests the certificate
              items:
                $ref: '#/components/schemas/BpnLocation'



    CertificateRequestFinishedResponse:
      type: object
      required:
        - header
        - content
      properties:
        header:
          $ref: '#/components/schemas/Header'
        content:
          oneOf:
            - $ref: '#/components/schemas/CertificateRequestCompletedResponseContent'
            - $ref: '#/components/schemas/CertificateRequestRejectedResponseContent'
          discriminator:
            propertyName: requestStatus

    CertificateRequestInProgressResponse:
      type: object
      required:
        - header
        - content
      properties:
        header:
          $ref: '#/components/schemas/Header'
        content:
          type: object
          required:
            - requestStatus
          properties:
            requestStatus:
              type: string
              description: The processing status in which the certificate request process is currently in
              const: "IN_PROGRESS"

    CertificateRequestCompletedResponseContent:
      type: object
      required:
        - requestStatus
        - documentId
      properties:
        requestStatus:
          type: string
          description: The processing status in which the certificate request process is currently in
          const: "COMPLETED"
        documentId:
          type: string
          pattern: uuid
          description: The UUID of the asset under which the certificate is available

    CertificateRequestRejectedResponseContent:
      type: object
      required:
        - requestStatus
        - requestErrors
      properties:
        requestStatus:
          type: string
          description: The processing status in which the certificate request process is currently in
          const: "REJECTED"
        requestErrors:
          type: array
          description: Listing all reasons why the requested certificate can not be provided
          items:
            $ref: '#/components/schemas/Error'
        locationErrors:
          type: array
          description: Optional detailed reasons for the rejection for each location
          items:
            $ref: '#/components/schemas/LocationErrorCollection'

    BpnLocation:
      type: string
      description: The BPNA or BPNS of either an address or site location
      pattern: "^BPN[AS][A-Z0-9]{12}$"
      examples:
        - "BPNA000000000001"
        - "BPNS000000000002"



    CertificatePush:
      type: object
      required:
        - header
        - content
      properties:
        header:
          $ref: '#/components/schemas/FeedbackUrlHeader'
        content:
          $ref: 'https://raw.githubusercontent.com/eclipse-tractusx/sldt-semantic-models/refs/heads/main/io.catenax.business_partner_certificate/3.1.0/gen/BusinessPartnerCertificate-schema.json'

    Error:
      type: object
      required:
        - message
      properties:
        message:
          type: string
          description: Text detailing the error that occured
          examples:
            - "We do not process certificates on Sunday"
            - "Can not provide certicate for requested locations"

    LocationErrorCollection:
      type: object
      properties:
        bpn:
          $ref: '#/components/schemas/BpnLocation'
        locationErrors:
          type: array
          items:
            $ref: '#/components/schemas/LocationError'

    LocationError:
      type: object
      properties:
        message:
          type: string
          examples:
            - Site BPNS000000000003 is unknown

    CertificateFeedback:
      type: object
      required:
        - header
        - content
      properties:
        header:
          $ref: '#/components/schemas/Header'
        content:
          type: object
          required:
            - documentId
            - certificateStatus
            - locationBpns
          properties:
            documentId:
              type: string
              format: uuid
            certificateStatus:
              type: string
              enum: [ACCEPTED, REJECTED, RECEIVED]
            certificateErrors:
              type: array
              items:
                $ref: '#/components/schemas/Error'
            locationBpns:
              type: array
              items:
                $ref: '#/components/schemas/BpnLocation'
            locationErrors:
              type: array
              items:
                $ref: '#/components/schemas/LocationErrorCollection'

    CertificateAvailable:
      type: object
      required:
        - header
        - content
      properties:
        header:
          $ref: '#/components/schemas/Header'
        content:
          type: object
          required:
            - documentId
            - certificateType
          properties:
            documentId:
              type: string
              format: uuid
            certificateType:
              type: string
              description: "Type of the certificate as defined on the document, valid types are registered at BPN metadatacontroller"
            locationBpns:
              type: array
              items:
                $ref: '#/components/schemas/BpnLocation'

  examples:
    CertificateRequestCompleted:
      summary: A response for a successfully completed certificate request process
      value:
        header:
          senderBpn: "BPNL0000000001AB"
          messagedId: "3b4edc05-e214-47a1-b0c2-1d831cdd9ba9"
          context: "CompanyCertificateManagement-CCMAPI-Request:1.0.0"
          receiverBpn: "BPNL0000000002CD"
          sentDateTime: "2025-05-04T00:00:00-07:00Z"
          version: "3.1.0"
        content:
          requestStatus: "COMPLETED"
          documentId: "3b4edc05-e214-47a1-b0c2-1d831cdd9ba"
    CertificateRequestRejected:
      summary: A response for a rejected certificate request process
      value:
        header:
          senderBpn: "BPNL0000000001AB"
          messagedId: "3b4edc05-e214-47a1-b0c2-1d831cdd9ba9"
          context: "CompanyCertificateManagement-CCMAPI-Request:1.0.0"
          receiverBpn: "BPNL0000000002CD"
          sentDateTime: "2025-05-04T00:00:00-07:00Z"
          version: "3.1.0"
        content:
          requestStatus: "REJECTED"
          requestErrors:
            - message: "We do not process certificates on Sunday"
            - message: "Can not provide certicate for requested locations"
          locationErrors:
            - bpn: "BPNS000000000003"
              locationErrors:
                - message: "Site BPNS000000000003 is unknown"
    CertificateAcceptedFeedback:
      summary: Consumer accepts received certificate
      value:
        header:
          senderBpn: "BPNL0000000001AB"
          messagedId: "3b4edc05-e214-47a1-b0c2-1d831cdd9ba9"
          context: "CompanyCertificateManagement-CCMAPI-Feedback:1.0.0"
          receiverBpn: "BPNL0000000002CD"
          sentDateTime: "2025-05-04T00:00:00-07:00Z"
          version: "3.1.0"
        content:
          documentId: "3fa85f64-5717-4562-b3fc-2c963f66afa6"
          certificateStatus: "ACCEPTED"
          locationBpns:
            - "BPNS000000000003"
    CertificateReceivedFeedback:
      summary: Consumer received certificate
      value:
        header:
          senderBpn: "BPNL0000000001AB"
          messagedId: "3b4edc05-e214-47a1-b0c2-1d831cdd9ba9"
          context: "CompanyCertificateManagement-CCMAPI-Feedback:1.0.0"
          receiverBpn: "BPNL0000000002CD"
          sentDateTime: "2025-05-04T00:00:00-07:00Z"
          version: "3.1.0"
        content:
          documentId: "3fa85f64-5717-4562-b3fc-2c963f66afa6"
          certificateStatus: "RECEIVED"
          locationBpns:
            - "BPNS000000000003"
    CertificateRejectedFeedback:
      summary: Consumer rejected received certificate
      value:
        header:
          senderBpn: "BPNL0000000001AB"
          messagedId: "3b4edc05-e214-47a1-b0c2-1d831cdd9ba9"
          context: "CompanyCertificateManagement-CCMAPI-Feedback:1.0.0"
          receiverBpn: "BPNL0000000002CD"
          sentDateTime: "2025-05-04T00:00:00-07:00Z"
          version: "3.1.0"
        content:
          documentId: "3fa85f64-5717-4562-b3fc-2c963f66afa6"
          certificateStatus: "REJECTED"
          locationBpns:
            - "BPNS000000000003"
          certificateErrors:
            - message: "We do not process certificates on Sunday"
            - message: "Can not provide certicate for requested locations"
          locationErrors:
            - bpn: "BPNS000000000003"
              locationErrors:
                - message: "Site BPNS000000000003 is unknown"

    CertificateAvailable:
      summary: Provider notifies consumer that a certificate is available
      value:
        header:
          senderBpn: "BPNL0000000001AB"
          messagedId: "3b4edc05-e214-47a1-b0c2-1d831cdd9ba9"
          context: "CompanyCertificateManagement-CCMAPI-Available:1.0.0"
          receiverBpn: "BPNL0000000002CD"
          sentDateTime: "2025-05-04T00:00:00-07:00Z"
          version: "3.1.0"
        content:
          documentId: "3fa85f64-5717-4562-b3fc-2c963f66afa6"
          certificateType: "iso9001"
          locationBpns:
            - "BPNS000000000003"



paths:
  /companycertificate/request:
    post:
      summary: Certificate consumer requests a specific certificate from certificate provider
      tags:
        - Certificate Provider
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CertificateRequest'
      responses:
        '202':
          description: Certificate request in processing
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CertificateRequestInProgressResponse'
        '200':
          description: Certificate request finished processing
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CertificateRequestFinishedResponse'
              examples:
                Completed:
                  $ref: '#/components/examples/CertificateRequestCompleted'
                Rejected:
                  $ref: '#/components/examples/CertificateRequestRejected'

        '400':
          description: Request malformed and can not be processed
        '500':
          description: Internal server error has occured

  /companycertificate/push:
    post:
      summary: Notify that a certificate is available along with its content
      tags:
        - Certificate Consumer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CertificatePush'
      responses:
        '200':
          description: Notification processed successfully

  /companycertificate/feedback:
    post:
      summary: Send feedback to an obtained certificate
      tags:
        - Certificate Provider
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CertificateFeedback'
            examples:
              Received:
                $ref: '#/components/examples/CertificateReceivedFeedback'
              Accepted:
                $ref: '#/components/examples/CertificateAcceptedFeedback'
              Rejected:
                $ref: '#/components/examples/CertificateRejectedFeedback'
      responses:
        '200':
          description: Feedback updated successfully

  /companycertificate/available:
    post:
      summary: Certificate provider notifies the certificate consumer that a certificate is available
      tags:
        - Certificate Consumer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CertificateAvailable'
      responses:
        '200':
          description: Notification processed successfully
